-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS CAKESHOP;

-- USE
USE CAKESHOP;

-- DROP IS EXISTS
DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS SELLERS;

-- CREATE TABLES
CREATE TABLE IF NOT EXISTS SELLERS(
	PRIMARY KEY(SELLERID) ,
    SELLERID INT NOT NULL,
    SELLERNAME CHAR(50),
    STARS FLOAT
    );
    
CREATE TABLE IF NOT EXISTS PRODUCTS(
	PRIMARY KEY(PRODUCTID),
    PRODUCTID INT NOT NULL,
    TITLE CHAR(120),
    ORIGINALPRICE FLOAT NOT NULL,
    DISCOUNT FLOAT NOT NULL,
    MAINPRICE FLOAT NOT NULL,
    LOWESTPRICE FLOAT,
    SUMMARIZE TEXT
    );

CREATE TABLE IF NOT EXISTS SALES(
	PRIMARY KEY(SALESID, PRODUCTID),
    SALESID INT NOT NULL,
	PRODUCTID INT NOT NULL,
    DATEDOM DATE NOT NULL,
    TIMEDOM TIME NOT NULL,
    SELLERID INT NOT NULL
    );
    
ALTER TABLE SALES ADD FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE;
ALTER TABLE SALES ADD FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID) ON UPDATE CASCADE;
ALTER TABLE SALES ADD FOREIGN KEY (SELLERID) REFERENCES SELLERS(SELLERID) ON DELETE CASCADE;
ALTER TABLE SALES ADD FOREIGN KEY (SELLERID) REFERENCES SELLERS(SELLERID) ON UPDATE CASCADE;

-- INSERT VALUES
INSERT INTO SELLERS VALUES 
(4001, "Adidas Company", 4.5);

INSERT INTO PRODUCTS VALUES 
(1001, "ADILETTE AQUA SLIDES", 150.00, 0.20, 120.00, 110.00, "");

INSERT INTO SALES VALUES 
(1020, 1001, "2021/02/03", "19:56:30", 4001);

