-- ------------------------
-- CREATE SIMULATION DATA 
-- ------------------------
DROP DATABASE IF EXISTS SIMULATION;
CREATE DATABASE IF NOT EXISTS SIMULATION;

USE SIMULATION;

CREATE TABLE IF NOT EXISTS VENTAS (
storeid int, 
productid int, 
day int, 
month int, 
year int, 
amount int,
date datetime
);

# WINDOW MOVIL AVERAGE 
SELECT STOREID, VENTAS.MONTH, AVG(AMOUNT) OVER W
FROM VENTAS
WHERE (VENTAS.MONTH BETWEEN 9 AND 12)  AND (VENTAS.YEAR = 2021)
WINDOW W AS (PARTITION BY STOREID ORDER BY VENTAS.MONTH ROWS 2 PRECEDING);




